package net.ray.web.ees.db.dao;

import net.ray.web.ees.db.eo.BrandMonthlyAchievement;

public interface BrandMonthlyAchievementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_brand_monthly_achievement
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_brand_monthly_achievement
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    int insert(BrandMonthlyAchievement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_brand_monthly_achievement
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    int insertSelective(BrandMonthlyAchievement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_brand_monthly_achievement
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    BrandMonthlyAchievement selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_brand_monthly_achievement
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    int updateByPrimaryKeySelective(BrandMonthlyAchievement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_brand_monthly_achievement
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    int updateByPrimaryKey(BrandMonthlyAchievement record);
}