package net.ray.web.ees.db.dao;

import net.ray.web.ees.db.eo.Holiday;

public interface HolidayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_holiday
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_holiday
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    int insert(Holiday record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_holiday
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    int insertSelective(Holiday record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_holiday
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    Holiday selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_holiday
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    int updateByPrimaryKeySelective(Holiday record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_holiday
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    int updateByPrimaryKey(Holiday record);
}