package net.ray.web.ees.db.dao;

import net.ray.web.ees.db.eo.MallBase;

public interface MallBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_mall_base
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_mall_base
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    int insert(MallBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_mall_base
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    int insertSelective(MallBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_mall_base
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    MallBase selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_mall_base
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    int updateByPrimaryKeySelective(MallBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_mall_base
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    int updateByPrimaryKey(MallBase record);
}