package net.ray.web.ees.db.dao;

import net.ray.web.ees.db.eo.RentType;

public interface RentTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_rent_type
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_rent_type
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    int insert(RentType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_rent_type
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    int insertSelective(RentType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_rent_type
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    RentType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_rent_type
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    int updateByPrimaryKeySelective(RentType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_rent_type
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    int updateByPrimaryKey(RentType record);
}