package net.ray.web.ees.db.dao;

import java.util.Date;
import java.util.List;
import java.util.Map;

import net.ray.web.ees.db.eo.TradeDailyAchievement;

public interface TradeDailyAchievementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_trade_daily_achievement
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_trade_daily_achievement
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    int insert(TradeDailyAchievement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_trade_daily_achievement
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    int insertSelective(TradeDailyAchievement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_trade_daily_achievement
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    TradeDailyAchievement selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_trade_daily_achievement
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    int updateByPrimaryKeySelective(TradeDailyAchievement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_trade_daily_achievement
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    int updateByPrimaryKey(TradeDailyAchievement record);
    
    List<TradeDailyAchievement> selectByDate(Date date);
    List<TradeDailyAchievement> selectByYesterday(Map<String,Object> map);
    Float countByYesterday();
    List<TradeDailyAchievement> selectByDurationAndTrade(Map<String,Object> map);
    Float countByDurationAndTrade(Map<String,Object> map);
}