package net.ray.web.ees.db.dao;

import java.util.List;

import net.ray.web.ees.db.eo.TradeYearAchievement;

public interface TradeYearAchievementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_trade_year_achievement
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_trade_year_achievement
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    int insert(TradeYearAchievement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_trade_year_achievement
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    int insertSelective(TradeYearAchievement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_trade_year_achievement
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    TradeYearAchievement selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_trade_year_achievement
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    int updateByPrimaryKeySelective(TradeYearAchievement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_trade_year_achievement
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    int updateByPrimaryKey(TradeYearAchievement record);
    
    List<TradeYearAchievement> selectBySelective(TradeYearAchievement tradeYearAchievement);
}