package net.ray.web.ees.db.dao;

import java.util.List;

import net.ray.web.ees.db.eo.TradeType;

public interface TradeTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_trade_type
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_trade_type
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    int insert(TradeType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_trade_type
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    int insertSelective(TradeType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_trade_type
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    TradeType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_trade_type
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    int updateByPrimaryKeySelective(TradeType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_trade_type
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    int updateByPrimaryKey(TradeType record);
    
    public List<TradeType> selectBySelective(TradeType para);
}