package net.ray.web.ees.db.eo;

import java.util.Date;

public class Authority {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_authority.id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_authority.person_id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Integer personId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_authority.menu_id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Integer menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_authority.creation_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Date creationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_authority.created_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_authority.update_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_authority.update_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_authority.isAlive
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Boolean isalive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_authority.id
     *
     * @return the value of e_authority.id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_authority.id
     *
     * @param id the value for e_authority.id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_authority.person_id
     *
     * @return the value of e_authority.person_id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Integer getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_authority.person_id
     *
     * @param personId the value for e_authority.person_id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setPersonId(Integer personId) {
        this.personId = personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_authority.menu_id
     *
     * @return the value of e_authority.menu_id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_authority.menu_id
     *
     * @param menuId the value for e_authority.menu_id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_authority.creation_date
     *
     * @return the value of e_authority.creation_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_authority.creation_date
     *
     * @param creationDate the value for e_authority.creation_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_authority.created_by
     *
     * @return the value of e_authority.created_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_authority.created_by
     *
     * @param createdBy the value for e_authority.created_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_authority.update_date
     *
     * @return the value of e_authority.update_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_authority.update_date
     *
     * @param updateDate the value for e_authority.update_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_authority.update_by
     *
     * @return the value of e_authority.update_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_authority.update_by
     *
     * @param updateBy the value for e_authority.update_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_authority.isAlive
     *
     * @return the value of e_authority.isAlive
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Boolean getIsalive() {
        return isalive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_authority.isAlive
     *
     * @param isalive the value for e_authority.isAlive
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setIsalive(Boolean isalive) {
        this.isalive = isalive;
    }
}