package net.ray.web.ees.db.eo;

import java.util.Date;

public class BrandYearAchievement {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_brand_year_achievement.id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_brand_year_achievement.brand_id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Integer brandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_brand_year_achievement.mall_id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Integer mallId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_brand_year_achievement.sale_year
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String saleYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_brand_year_achievement.sales_amount
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Float salesAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_brand_year_achievement.sales_volume
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Integer salesVolume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_brand_year_achievement.sales_times
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Integer salesTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_brand_year_achievement.y_rent
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Float yRent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_brand_year_achievement.y_property
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Float yProperty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_brand_year_achievement.y_other_charge1
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Float yOtherCharge1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_brand_year_achievement.y_other_charge2
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Float yOtherCharge2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_brand_year_achievement.y_other_charge3
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Float yOtherCharge3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_brand_year_achievement.y_fixed_charge1
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Float yFixedCharge1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_brand_year_achievement.y_fixed_charge2
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Float yFixedCharge2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_brand_year_achievement.y_fixed_charge3
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Float yFixedCharge3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_brand_year_achievement.update_dates
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Date updateDates;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_brand_year_achievement.creation_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Date creationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_brand_year_achievement.created_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_brand_year_achievement.update_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_brand_year_achievement.updated_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_brand_year_achievement.is_alive
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Boolean isAlive;
	private Integer customerVolume;
	private Integer carVolume;
	private String weather;
	
	
    public String getWeather() {
		return weather;
	}

	public void setWeather(String weather) {
		this.weather = weather;
	}

	public Integer getCustomerVolume() {
		return customerVolume;
	}

	public void setCustomerVolume(Integer customerVolume) {
		this.customerVolume = customerVolume;
	}

	public Integer getCarVolume() {
		return carVolume;
	}

	public void setCarVolume(Integer carVolume) {
		this.carVolume = carVolume;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_brand_year_achievement.id
     *
     * @return the value of e_brand_year_achievement.id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_brand_year_achievement.id
     *
     * @param id the value for e_brand_year_achievement.id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_brand_year_achievement.brand_id
     *
     * @return the value of e_brand_year_achievement.brand_id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_brand_year_achievement.brand_id
     *
     * @param brandId the value for e_brand_year_achievement.brand_id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_brand_year_achievement.mall_id
     *
     * @return the value of e_brand_year_achievement.mall_id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Integer getMallId() {
        return mallId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_brand_year_achievement.mall_id
     *
     * @param mallId the value for e_brand_year_achievement.mall_id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setMallId(Integer mallId) {
        this.mallId = mallId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_brand_year_achievement.sale_year
     *
     * @return the value of e_brand_year_achievement.sale_year
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getSaleYear() {
        return saleYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_brand_year_achievement.sale_year
     *
     * @param saleYear the value for e_brand_year_achievement.sale_year
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setSaleYear(String saleYear) {
        this.saleYear = saleYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_brand_year_achievement.sales_amount
     *
     * @return the value of e_brand_year_achievement.sales_amount
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Float getSalesAmount() {
        return salesAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_brand_year_achievement.sales_amount
     *
     * @param salesAmount the value for e_brand_year_achievement.sales_amount
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setSalesAmount(Float salesAmount) {
        this.salesAmount = salesAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_brand_year_achievement.sales_volume
     *
     * @return the value of e_brand_year_achievement.sales_volume
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Integer getSalesVolume() {
        return salesVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_brand_year_achievement.sales_volume
     *
     * @param salesVolume the value for e_brand_year_achievement.sales_volume
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setSalesVolume(Integer salesVolume) {
        this.salesVolume = salesVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_brand_year_achievement.sales_times
     *
     * @return the value of e_brand_year_achievement.sales_times
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Integer getSalesTimes() {
        return salesTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_brand_year_achievement.sales_times
     *
     * @param salesTimes the value for e_brand_year_achievement.sales_times
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setSalesTimes(Integer salesTimes) {
        this.salesTimes = salesTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_brand_year_achievement.y_rent
     *
     * @return the value of e_brand_year_achievement.y_rent
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Float getyRent() {
        return yRent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_brand_year_achievement.y_rent
     *
     * @param yRent the value for e_brand_year_achievement.y_rent
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setyRent(Float yRent) {
        this.yRent = yRent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_brand_year_achievement.y_property
     *
     * @return the value of e_brand_year_achievement.y_property
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Float getyProperty() {
        return yProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_brand_year_achievement.y_property
     *
     * @param yProperty the value for e_brand_year_achievement.y_property
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setyProperty(Float yProperty) {
        this.yProperty = yProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_brand_year_achievement.y_other_charge1
     *
     * @return the value of e_brand_year_achievement.y_other_charge1
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Float getyOtherCharge1() {
        return yOtherCharge1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_brand_year_achievement.y_other_charge1
     *
     * @param yOtherCharge1 the value for e_brand_year_achievement.y_other_charge1
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setyOtherCharge1(Float yOtherCharge1) {
        this.yOtherCharge1 = yOtherCharge1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_brand_year_achievement.y_other_charge2
     *
     * @return the value of e_brand_year_achievement.y_other_charge2
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Float getyOtherCharge2() {
        return yOtherCharge2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_brand_year_achievement.y_other_charge2
     *
     * @param yOtherCharge2 the value for e_brand_year_achievement.y_other_charge2
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setyOtherCharge2(Float yOtherCharge2) {
        this.yOtherCharge2 = yOtherCharge2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_brand_year_achievement.y_other_charge3
     *
     * @return the value of e_brand_year_achievement.y_other_charge3
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Float getyOtherCharge3() {
        return yOtherCharge3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_brand_year_achievement.y_other_charge3
     *
     * @param yOtherCharge3 the value for e_brand_year_achievement.y_other_charge3
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setyOtherCharge3(Float yOtherCharge3) {
        this.yOtherCharge3 = yOtherCharge3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_brand_year_achievement.y_fixed_charge1
     *
     * @return the value of e_brand_year_achievement.y_fixed_charge1
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Float getyFixedCharge1() {
        return yFixedCharge1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_brand_year_achievement.y_fixed_charge1
     *
     * @param yFixedCharge1 the value for e_brand_year_achievement.y_fixed_charge1
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setyFixedCharge1(Float yFixedCharge1) {
        this.yFixedCharge1 = yFixedCharge1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_brand_year_achievement.y_fixed_charge2
     *
     * @return the value of e_brand_year_achievement.y_fixed_charge2
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Float getyFixedCharge2() {
        return yFixedCharge2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_brand_year_achievement.y_fixed_charge2
     *
     * @param yFixedCharge2 the value for e_brand_year_achievement.y_fixed_charge2
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setyFixedCharge2(Float yFixedCharge2) {
        this.yFixedCharge2 = yFixedCharge2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_brand_year_achievement.y_fixed_charge3
     *
     * @return the value of e_brand_year_achievement.y_fixed_charge3
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Float getyFixedCharge3() {
        return yFixedCharge3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_brand_year_achievement.y_fixed_charge3
     *
     * @param yFixedCharge3 the value for e_brand_year_achievement.y_fixed_charge3
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setyFixedCharge3(Float yFixedCharge3) {
        this.yFixedCharge3 = yFixedCharge3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_brand_year_achievement.update_dates
     *
     * @return the value of e_brand_year_achievement.update_dates
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Date getUpdateDates() {
        return updateDates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_brand_year_achievement.update_dates
     *
     * @param updateDates the value for e_brand_year_achievement.update_dates
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setUpdateDates(Date updateDates) {
        this.updateDates = updateDates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_brand_year_achievement.creation_date
     *
     * @return the value of e_brand_year_achievement.creation_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_brand_year_achievement.creation_date
     *
     * @param creationDate the value for e_brand_year_achievement.creation_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_brand_year_achievement.created_by
     *
     * @return the value of e_brand_year_achievement.created_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_brand_year_achievement.created_by
     *
     * @param createdBy the value for e_brand_year_achievement.created_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_brand_year_achievement.update_date
     *
     * @return the value of e_brand_year_achievement.update_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_brand_year_achievement.update_date
     *
     * @param updateDate the value for e_brand_year_achievement.update_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_brand_year_achievement.updated_by
     *
     * @return the value of e_brand_year_achievement.updated_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_brand_year_achievement.updated_by
     *
     * @param updatedBy the value for e_brand_year_achievement.updated_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_brand_year_achievement.is_alive
     *
     * @return the value of e_brand_year_achievement.is_alive
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Boolean getIsAlive() {
        return isAlive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_brand_year_achievement.is_alive
     *
     * @param isAlive the value for e_brand_year_achievement.is_alive
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setIsAlive(Boolean isAlive) {
        this.isAlive = isAlive;
    }
}