package net.ray.web.ees.db.eo;

import java.util.Date;

public class BrandInfro {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column e_brand_info.id
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	private Integer id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column e_brand_info.poi_num
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	private String poiNum;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column e_brand_info.floor
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	private String floor;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column e_brand_info.brand_id_root
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	private Integer brandIdRoot;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column e_brand_info.brand_id_level1
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	private Integer brandIdLevel1;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column e_brand_info.brand_id_level2
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	private Integer brandIdLevel2;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column e_brand_info.rent_type
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	private String rentType;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column e_brand_info.fixed_rent
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	private String fixedRent;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column e_brand_info.fixed_rent_standard
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	private String fixedRentStandard;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column e_brand_info.com_rent_standard
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	private String comRentStandard;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column e_brand_info.property_standard
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	private String propertyStandard;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column e_brand_info.property
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	private String property;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column e_brand_info.fixed_property
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	private String fixedProperty;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column e_brand_info.other_charge_std1
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	private String otherChargeStd1;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column e_brand_info.other_charge_std2
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	private String otherChargeStd2;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column e_brand_info.other_charge_std3
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	private String otherChargeStd3;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column e_brand_info.other_charge1
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	private String otherCharge1;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column e_brand_info.other_charge2
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	private String otherCharge2;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column e_brand_info.other_charge3
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	private String otherCharge3;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column e_brand_info.other_fixed_charge1
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	private String otherFixedCharge1;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column e_brand_info.other_fixed_charge2
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	private String otherFixedCharge2;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column e_brand_info.other_fixed_charge3
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	private String otherFixedCharge3;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column e_brand_info.table_num
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	private Integer tableNum;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column e_brand_info.seats_num
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	private Integer seatsNum;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column e_brand_info.oper_state
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	private String operState;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column e_brand_info.oper_type
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	private String operType;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column e_brand_info.lease_type
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	private String leaseType;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column e_brand_info.start_time
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	private Date startTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column e_brand_info.close_time
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	private Date closeTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column e_brand_info.creation_date
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	private Date creationDate;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column e_brand_info.created_by
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	private String createdBy;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column e_brand_info.update_date
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	private Date updateDate;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column e_brand_info.update_by
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	private String updateBy;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column e_brand_info.is_alive
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	private Boolean isAlive;
	private String brandName;

	public String getBrandName() {
		return brandName;
	}

	public void setBrandName(String brandName) {
		this.brandName = brandName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column e_brand_info.id
	 *
	 * @return the value of e_brand_info.id
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column e_brand_info.id
	 *
	 * @param id
	 *            the value for e_brand_info.id
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column e_brand_info.poi_num
	 *
	 * @return the value of e_brand_info.poi_num
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public String getPoiNum() {
		return poiNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column e_brand_info.poi_num
	 *
	 * @param poiNum
	 *            the value for e_brand_info.poi_num
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public void setPoiNum(String poiNum) {
		this.poiNum = poiNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column e_brand_info.floor
	 *
	 * @return the value of e_brand_info.floor
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public String getFloor() {
		return floor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column e_brand_info.floor
	 *
	 * @param floor
	 *            the value for e_brand_info.floor
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public void setFloor(String floor) {
		this.floor = floor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column e_brand_info.brand_id_root
	 *
	 * @return the value of e_brand_info.brand_id_root
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public Integer getBrandIdRoot() {
		return brandIdRoot;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column e_brand_info.brand_id_root
	 *
	 * @param brandIdRoot
	 *            the value for e_brand_info.brand_id_root
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public void setBrandIdRoot(Integer brandIdRoot) {
		this.brandIdRoot = brandIdRoot;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column e_brand_info.brand_id_level1
	 *
	 * @return the value of e_brand_info.brand_id_level1
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public Integer getBrandIdLevel1() {
		return brandIdLevel1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column e_brand_info.brand_id_level1
	 *
	 * @param brandIdLevel1
	 *            the value for e_brand_info.brand_id_level1
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public void setBrandIdLevel1(Integer brandIdLevel1) {
		this.brandIdLevel1 = brandIdLevel1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column e_brand_info.brand_id_level2
	 *
	 * @return the value of e_brand_info.brand_id_level2
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public Integer getBrandIdLevel2() {
		return brandIdLevel2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column e_brand_info.brand_id_level2
	 *
	 * @param brandIdLevel2
	 *            the value for e_brand_info.brand_id_level2
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public void setBrandIdLevel2(Integer brandIdLevel2) {
		this.brandIdLevel2 = brandIdLevel2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column e_brand_info.rent_type
	 *
	 * @return the value of e_brand_info.rent_type
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public String getRentType() {
		return rentType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column e_brand_info.rent_type
	 *
	 * @param rentType
	 *            the value for e_brand_info.rent_type
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public void setRentType(String rentType) {
		this.rentType = rentType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column e_brand_info.fixed_rent
	 *
	 * @return the value of e_brand_info.fixed_rent
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public String getFixedRent() {
		return fixedRent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column e_brand_info.fixed_rent
	 *
	 * @param fixedRent
	 *            the value for e_brand_info.fixed_rent
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public void setFixedRent(String fixedRent) {
		this.fixedRent = fixedRent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column e_brand_info.fixed_rent_standard
	 *
	 * @return the value of e_brand_info.fixed_rent_standard
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public String getFixedRentStandard() {
		return fixedRentStandard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column e_brand_info.fixed_rent_standard
	 *
	 * @param fixedRentStandard
	 *            the value for e_brand_info.fixed_rent_standard
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public void setFixedRentStandard(String fixedRentStandard) {
		this.fixedRentStandard = fixedRentStandard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column e_brand_info.com_rent_standard
	 *
	 * @return the value of e_brand_info.com_rent_standard
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public String getComRentStandard() {
		return comRentStandard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column e_brand_info.com_rent_standard
	 *
	 * @param comRentStandard
	 *            the value for e_brand_info.com_rent_standard
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public void setComRentStandard(String comRentStandard) {
		this.comRentStandard = comRentStandard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column e_brand_info.property_standard
	 *
	 * @return the value of e_brand_info.property_standard
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public String getPropertyStandard() {
		return propertyStandard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column e_brand_info.property_standard
	 *
	 * @param propertyStandard
	 *            the value for e_brand_info.property_standard
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public void setPropertyStandard(String propertyStandard) {
		this.propertyStandard = propertyStandard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column e_brand_info.property
	 *
	 * @return the value of e_brand_info.property
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public String getProperty() {
		return property;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column e_brand_info.property
	 *
	 * @param property
	 *            the value for e_brand_info.property
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public void setProperty(String property) {
		this.property = property;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column e_brand_info.fixed_property
	 *
	 * @return the value of e_brand_info.fixed_property
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public String getFixedProperty() {
		return fixedProperty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column e_brand_info.fixed_property
	 *
	 * @param fixedProperty
	 *            the value for e_brand_info.fixed_property
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public void setFixedProperty(String fixedProperty) {
		this.fixedProperty = fixedProperty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column e_brand_info.other_charge_std1
	 *
	 * @return the value of e_brand_info.other_charge_std1
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public String getOtherChargeStd1() {
		return otherChargeStd1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column e_brand_info.other_charge_std1
	 *
	 * @param otherChargeStd1
	 *            the value for e_brand_info.other_charge_std1
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public void setOtherChargeStd1(String otherChargeStd1) {
		this.otherChargeStd1 = otherChargeStd1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column e_brand_info.other_charge_std2
	 *
	 * @return the value of e_brand_info.other_charge_std2
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public String getOtherChargeStd2() {
		return otherChargeStd2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column e_brand_info.other_charge_std2
	 *
	 * @param otherChargeStd2
	 *            the value for e_brand_info.other_charge_std2
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public void setOtherChargeStd2(String otherChargeStd2) {
		this.otherChargeStd2 = otherChargeStd2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column e_brand_info.other_charge_std3
	 *
	 * @return the value of e_brand_info.other_charge_std3
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public String getOtherChargeStd3() {
		return otherChargeStd3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column e_brand_info.other_charge_std3
	 *
	 * @param otherChargeStd3
	 *            the value for e_brand_info.other_charge_std3
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public void setOtherChargeStd3(String otherChargeStd3) {
		this.otherChargeStd3 = otherChargeStd3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column e_brand_info.other_charge1
	 *
	 * @return the value of e_brand_info.other_charge1
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public String getOtherCharge1() {
		return otherCharge1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column e_brand_info.other_charge1
	 *
	 * @param otherCharge1
	 *            the value for e_brand_info.other_charge1
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public void setOtherCharge1(String otherCharge1) {
		this.otherCharge1 = otherCharge1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column e_brand_info.other_charge2
	 *
	 * @return the value of e_brand_info.other_charge2
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public String getOtherCharge2() {
		return otherCharge2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column e_brand_info.other_charge2
	 *
	 * @param otherCharge2
	 *            the value for e_brand_info.other_charge2
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public void setOtherCharge2(String otherCharge2) {
		this.otherCharge2 = otherCharge2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column e_brand_info.other_charge3
	 *
	 * @return the value of e_brand_info.other_charge3
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public String getOtherCharge3() {
		return otherCharge3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column e_brand_info.other_charge3
	 *
	 * @param otherCharge3
	 *            the value for e_brand_info.other_charge3
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public void setOtherCharge3(String otherCharge3) {
		this.otherCharge3 = otherCharge3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column e_brand_info.other_fixed_charge1
	 *
	 * @return the value of e_brand_info.other_fixed_charge1
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public String getOtherFixedCharge1() {
		return otherFixedCharge1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column e_brand_info.other_fixed_charge1
	 *
	 * @param otherFixedCharge1
	 *            the value for e_brand_info.other_fixed_charge1
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public void setOtherFixedCharge1(String otherFixedCharge1) {
		this.otherFixedCharge1 = otherFixedCharge1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column e_brand_info.other_fixed_charge2
	 *
	 * @return the value of e_brand_info.other_fixed_charge2
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public String getOtherFixedCharge2() {
		return otherFixedCharge2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column e_brand_info.other_fixed_charge2
	 *
	 * @param otherFixedCharge2
	 *            the value for e_brand_info.other_fixed_charge2
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public void setOtherFixedCharge2(String otherFixedCharge2) {
		this.otherFixedCharge2 = otherFixedCharge2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column e_brand_info.other_fixed_charge3
	 *
	 * @return the value of e_brand_info.other_fixed_charge3
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public String getOtherFixedCharge3() {
		return otherFixedCharge3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column e_brand_info.other_fixed_charge3
	 *
	 * @param otherFixedCharge3
	 *            the value for e_brand_info.other_fixed_charge3
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public void setOtherFixedCharge3(String otherFixedCharge3) {
		this.otherFixedCharge3 = otherFixedCharge3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column e_brand_info.table_num
	 *
	 * @return the value of e_brand_info.table_num
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public Integer getTableNum() {
		return tableNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column e_brand_info.table_num
	 *
	 * @param tableNum
	 *            the value for e_brand_info.table_num
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public void setTableNum(Integer tableNum) {
		this.tableNum = tableNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column e_brand_info.seats_num
	 *
	 * @return the value of e_brand_info.seats_num
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public Integer getSeatsNum() {
		return seatsNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column e_brand_info.seats_num
	 *
	 * @param seatsNum
	 *            the value for e_brand_info.seats_num
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public void setSeatsNum(Integer seatsNum) {
		this.seatsNum = seatsNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column e_brand_info.oper_state
	 *
	 * @return the value of e_brand_info.oper_state
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public String getOperState() {
		return operState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column e_brand_info.oper_state
	 *
	 * @param operState
	 *            the value for e_brand_info.oper_state
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public void setOperState(String operState) {
		this.operState = operState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column e_brand_info.oper_type
	 *
	 * @return the value of e_brand_info.oper_type
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public String getOperType() {
		return operType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column e_brand_info.oper_type
	 *
	 * @param operType
	 *            the value for e_brand_info.oper_type
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public void setOperType(String operType) {
		this.operType = operType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column e_brand_info.lease_type
	 *
	 * @return the value of e_brand_info.lease_type
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public String getLeaseType() {
		return leaseType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column e_brand_info.lease_type
	 *
	 * @param leaseType
	 *            the value for e_brand_info.lease_type
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public void setLeaseType(String leaseType) {
		this.leaseType = leaseType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column e_brand_info.start_time
	 *
	 * @return the value of e_brand_info.start_time
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public Date getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column e_brand_info.start_time
	 *
	 * @param startTime
	 *            the value for e_brand_info.start_time
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column e_brand_info.close_time
	 *
	 * @return the value of e_brand_info.close_time
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public Date getCloseTime() {
		return closeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column e_brand_info.close_time
	 *
	 * @param closeTime
	 *            the value for e_brand_info.close_time
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public void setCloseTime(Date closeTime) {
		this.closeTime = closeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column e_brand_info.creation_date
	 *
	 * @return the value of e_brand_info.creation_date
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public Date getCreationDate() {
		return creationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column e_brand_info.creation_date
	 *
	 * @param creationDate
	 *            the value for e_brand_info.creation_date
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column e_brand_info.created_by
	 *
	 * @return the value of e_brand_info.created_by
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public String getCreatedBy() {
		return createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column e_brand_info.created_by
	 *
	 * @param createdBy
	 *            the value for e_brand_info.created_by
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column e_brand_info.update_date
	 *
	 * @return the value of e_brand_info.update_date
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column e_brand_info.update_date
	 *
	 * @param updateDate
	 *            the value for e_brand_info.update_date
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column e_brand_info.update_by
	 *
	 * @return the value of e_brand_info.update_by
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public String getUpdateBy() {
		return updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column e_brand_info.update_by
	 *
	 * @param updateBy
	 *            the value for e_brand_info.update_by
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column e_brand_info.is_alive
	 *
	 * @return the value of e_brand_info.is_alive
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public Boolean getIsAlive() {
		return isAlive;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column e_brand_info.is_alive
	 *
	 * @param isAlive
	 *            the value for e_brand_info.is_alive
	 *
	 * @mbg.generated Thu Nov 24 17:04:55 CST 2016
	 */
	public void setIsAlive(Boolean isAlive) {
		this.isAlive = isAlive;
	}
}