package net.ray.web.ees.db.eo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BrandDailyAchievementExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table e_brand_daily_achievement
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table e_brand_daily_achievement
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table e_brand_daily_achievement
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_brand_daily_achievement
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public BrandDailyAchievementExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_brand_daily_achievement
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_brand_daily_achievement
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_brand_daily_achievement
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_brand_daily_achievement
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_brand_daily_achievement
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_brand_daily_achievement
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_brand_daily_achievement
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_brand_daily_achievement
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_brand_daily_achievement
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_brand_daily_achievement
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table e_brand_daily_achievement
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andBrandIdIsNull() {
            addCriterion("brand_id is null");
            return (Criteria) this;
        }

        public Criteria andBrandIdIsNotNull() {
            addCriterion("brand_id is not null");
            return (Criteria) this;
        }

        public Criteria andBrandIdEqualTo(Integer value) {
            addCriterion("brand_id =", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdNotEqualTo(Integer value) {
            addCriterion("brand_id <>", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdGreaterThan(Integer value) {
            addCriterion("brand_id >", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("brand_id >=", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdLessThan(Integer value) {
            addCriterion("brand_id <", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdLessThanOrEqualTo(Integer value) {
            addCriterion("brand_id <=", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdIn(List<Integer> values) {
            addCriterion("brand_id in", values, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdNotIn(List<Integer> values) {
            addCriterion("brand_id not in", values, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdBetween(Integer value1, Integer value2) {
            addCriterion("brand_id between", value1, value2, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdNotBetween(Integer value1, Integer value2) {
            addCriterion("brand_id not between", value1, value2, "brandId");
            return (Criteria) this;
        }

        public Criteria andMallIdIsNull() {
            addCriterion("mall_id is null");
            return (Criteria) this;
        }

        public Criteria andMallIdIsNotNull() {
            addCriterion("mall_id is not null");
            return (Criteria) this;
        }

        public Criteria andMallIdEqualTo(Integer value) {
            addCriterion("mall_id =", value, "mallId");
            return (Criteria) this;
        }

        public Criteria andMallIdNotEqualTo(Integer value) {
            addCriterion("mall_id <>", value, "mallId");
            return (Criteria) this;
        }

        public Criteria andMallIdGreaterThan(Integer value) {
            addCriterion("mall_id >", value, "mallId");
            return (Criteria) this;
        }

        public Criteria andMallIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("mall_id >=", value, "mallId");
            return (Criteria) this;
        }

        public Criteria andMallIdLessThan(Integer value) {
            addCriterion("mall_id <", value, "mallId");
            return (Criteria) this;
        }

        public Criteria andMallIdLessThanOrEqualTo(Integer value) {
            addCriterion("mall_id <=", value, "mallId");
            return (Criteria) this;
        }

        public Criteria andMallIdIn(List<Integer> values) {
            addCriterion("mall_id in", values, "mallId");
            return (Criteria) this;
        }

        public Criteria andMallIdNotIn(List<Integer> values) {
            addCriterion("mall_id not in", values, "mallId");
            return (Criteria) this;
        }

        public Criteria andMallIdBetween(Integer value1, Integer value2) {
            addCriterion("mall_id between", value1, value2, "mallId");
            return (Criteria) this;
        }

        public Criteria andMallIdNotBetween(Integer value1, Integer value2) {
            addCriterion("mall_id not between", value1, value2, "mallId");
            return (Criteria) this;
        }

        public Criteria andSalesDateIsNull() {
            addCriterion("sales_date is null");
            return (Criteria) this;
        }

        public Criteria andSalesDateIsNotNull() {
            addCriterion("sales_date is not null");
            return (Criteria) this;
        }

        public Criteria andSalesDateEqualTo(Date value) {
            addCriterion("sales_date =", value, "salesDate");
            return (Criteria) this;
        }

        public Criteria andSalesDateNotEqualTo(Date value) {
            addCriterion("sales_date <>", value, "salesDate");
            return (Criteria) this;
        }

        public Criteria andSalesDateGreaterThan(Date value) {
            addCriterion("sales_date >", value, "salesDate");
            return (Criteria) this;
        }

        public Criteria andSalesDateGreaterThanOrEqualTo(Date value) {
            addCriterion("sales_date >=", value, "salesDate");
            return (Criteria) this;
        }

        public Criteria andSalesDateLessThan(Date value) {
            addCriterion("sales_date <", value, "salesDate");
            return (Criteria) this;
        }

        public Criteria andSalesDateLessThanOrEqualTo(Date value) {
            addCriterion("sales_date <=", value, "salesDate");
            return (Criteria) this;
        }

        public Criteria andSalesDateIn(List<Date> values) {
            addCriterion("sales_date in", values, "salesDate");
            return (Criteria) this;
        }

        public Criteria andSalesDateNotIn(List<Date> values) {
            addCriterion("sales_date not in", values, "salesDate");
            return (Criteria) this;
        }

        public Criteria andSalesDateBetween(Date value1, Date value2) {
            addCriterion("sales_date between", value1, value2, "salesDate");
            return (Criteria) this;
        }

        public Criteria andSalesDateNotBetween(Date value1, Date value2) {
            addCriterion("sales_date not between", value1, value2, "salesDate");
            return (Criteria) this;
        }

        public Criteria andSalesofamountIsNull() {
            addCriterion("salesofamount is null");
            return (Criteria) this;
        }

        public Criteria andSalesofamountIsNotNull() {
            addCriterion("salesofamount is not null");
            return (Criteria) this;
        }

        public Criteria andSalesofamountEqualTo(Float value) {
            addCriterion("salesofamount =", value, "salesofamount");
            return (Criteria) this;
        }

        public Criteria andSalesofamountNotEqualTo(Float value) {
            addCriterion("salesofamount <>", value, "salesofamount");
            return (Criteria) this;
        }

        public Criteria andSalesofamountGreaterThan(Float value) {
            addCriterion("salesofamount >", value, "salesofamount");
            return (Criteria) this;
        }

        public Criteria andSalesofamountGreaterThanOrEqualTo(Float value) {
            addCriterion("salesofamount >=", value, "salesofamount");
            return (Criteria) this;
        }

        public Criteria andSalesofamountLessThan(Float value) {
            addCriterion("salesofamount <", value, "salesofamount");
            return (Criteria) this;
        }

        public Criteria andSalesofamountLessThanOrEqualTo(Float value) {
            addCriterion("salesofamount <=", value, "salesofamount");
            return (Criteria) this;
        }

        public Criteria andSalesofamountIn(List<Float> values) {
            addCriterion("salesofamount in", values, "salesofamount");
            return (Criteria) this;
        }

        public Criteria andSalesofamountNotIn(List<Float> values) {
            addCriterion("salesofamount not in", values, "salesofamount");
            return (Criteria) this;
        }

        public Criteria andSalesofamountBetween(Float value1, Float value2) {
            addCriterion("salesofamount between", value1, value2, "salesofamount");
            return (Criteria) this;
        }

        public Criteria andSalesofamountNotBetween(Float value1, Float value2) {
            addCriterion("salesofamount not between", value1, value2, "salesofamount");
            return (Criteria) this;
        }

        public Criteria andSalesVolumeIsNull() {
            addCriterion("sales_volume is null");
            return (Criteria) this;
        }

        public Criteria andSalesVolumeIsNotNull() {
            addCriterion("sales_volume is not null");
            return (Criteria) this;
        }

        public Criteria andSalesVolumeEqualTo(Float value) {
            addCriterion("sales_volume =", value, "salesVolume");
            return (Criteria) this;
        }

        public Criteria andSalesVolumeNotEqualTo(Float value) {
            addCriterion("sales_volume <>", value, "salesVolume");
            return (Criteria) this;
        }

        public Criteria andSalesVolumeGreaterThan(Float value) {
            addCriterion("sales_volume >", value, "salesVolume");
            return (Criteria) this;
        }

        public Criteria andSalesVolumeGreaterThanOrEqualTo(Float value) {
            addCriterion("sales_volume >=", value, "salesVolume");
            return (Criteria) this;
        }

        public Criteria andSalesVolumeLessThan(Float value) {
            addCriterion("sales_volume <", value, "salesVolume");
            return (Criteria) this;
        }

        public Criteria andSalesVolumeLessThanOrEqualTo(Float value) {
            addCriterion("sales_volume <=", value, "salesVolume");
            return (Criteria) this;
        }

        public Criteria andSalesVolumeIn(List<Float> values) {
            addCriterion("sales_volume in", values, "salesVolume");
            return (Criteria) this;
        }

        public Criteria andSalesVolumeNotIn(List<Float> values) {
            addCriterion("sales_volume not in", values, "salesVolume");
            return (Criteria) this;
        }

        public Criteria andSalesVolumeBetween(Float value1, Float value2) {
            addCriterion("sales_volume between", value1, value2, "salesVolume");
            return (Criteria) this;
        }

        public Criteria andSalesVolumeNotBetween(Float value1, Float value2) {
            addCriterion("sales_volume not between", value1, value2, "salesVolume");
            return (Criteria) this;
        }

        public Criteria andSalesTimesIsNull() {
            addCriterion("sales_times is null");
            return (Criteria) this;
        }

        public Criteria andSalesTimesIsNotNull() {
            addCriterion("sales_times is not null");
            return (Criteria) this;
        }

        public Criteria andSalesTimesEqualTo(Integer value) {
            addCriterion("sales_times =", value, "salesTimes");
            return (Criteria) this;
        }

        public Criteria andSalesTimesNotEqualTo(Integer value) {
            addCriterion("sales_times <>", value, "salesTimes");
            return (Criteria) this;
        }

        public Criteria andSalesTimesGreaterThan(Integer value) {
            addCriterion("sales_times >", value, "salesTimes");
            return (Criteria) this;
        }

        public Criteria andSalesTimesGreaterThanOrEqualTo(Integer value) {
            addCriterion("sales_times >=", value, "salesTimes");
            return (Criteria) this;
        }

        public Criteria andSalesTimesLessThan(Integer value) {
            addCriterion("sales_times <", value, "salesTimes");
            return (Criteria) this;
        }

        public Criteria andSalesTimesLessThanOrEqualTo(Integer value) {
            addCriterion("sales_times <=", value, "salesTimes");
            return (Criteria) this;
        }

        public Criteria andSalesTimesIn(List<Integer> values) {
            addCriterion("sales_times in", values, "salesTimes");
            return (Criteria) this;
        }

        public Criteria andSalesTimesNotIn(List<Integer> values) {
            addCriterion("sales_times not in", values, "salesTimes");
            return (Criteria) this;
        }

        public Criteria andSalesTimesBetween(Integer value1, Integer value2) {
            addCriterion("sales_times between", value1, value2, "salesTimes");
            return (Criteria) this;
        }

        public Criteria andSalesTimesNotBetween(Integer value1, Integer value2) {
            addCriterion("sales_times not between", value1, value2, "salesTimes");
            return (Criteria) this;
        }

        public Criteria andIsHolidayIsNull() {
            addCriterion("is_holiday is null");
            return (Criteria) this;
        }

        public Criteria andIsHolidayIsNotNull() {
            addCriterion("is_holiday is not null");
            return (Criteria) this;
        }

        public Criteria andIsHolidayEqualTo(Boolean value) {
            addCriterion("is_holiday =", value, "isHoliday");
            return (Criteria) this;
        }

        public Criteria andIsHolidayNotEqualTo(Boolean value) {
            addCriterion("is_holiday <>", value, "isHoliday");
            return (Criteria) this;
        }

        public Criteria andIsHolidayGreaterThan(Boolean value) {
            addCriterion("is_holiday >", value, "isHoliday");
            return (Criteria) this;
        }

        public Criteria andIsHolidayGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_holiday >=", value, "isHoliday");
            return (Criteria) this;
        }

        public Criteria andIsHolidayLessThan(Boolean value) {
            addCriterion("is_holiday <", value, "isHoliday");
            return (Criteria) this;
        }

        public Criteria andIsHolidayLessThanOrEqualTo(Boolean value) {
            addCriterion("is_holiday <=", value, "isHoliday");
            return (Criteria) this;
        }

        public Criteria andIsHolidayIn(List<Boolean> values) {
            addCriterion("is_holiday in", values, "isHoliday");
            return (Criteria) this;
        }

        public Criteria andIsHolidayNotIn(List<Boolean> values) {
            addCriterion("is_holiday not in", values, "isHoliday");
            return (Criteria) this;
        }

        public Criteria andIsHolidayBetween(Boolean value1, Boolean value2) {
            addCriterion("is_holiday between", value1, value2, "isHoliday");
            return (Criteria) this;
        }

        public Criteria andIsHolidayNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_holiday not between", value1, value2, "isHoliday");
            return (Criteria) this;
        }

        public Criteria andHolidayIdIsNull() {
            addCriterion("holiday_id is null");
            return (Criteria) this;
        }

        public Criteria andHolidayIdIsNotNull() {
            addCriterion("holiday_id is not null");
            return (Criteria) this;
        }

        public Criteria andHolidayIdEqualTo(String value) {
            addCriterion("holiday_id =", value, "holidayId");
            return (Criteria) this;
        }

        public Criteria andHolidayIdNotEqualTo(String value) {
            addCriterion("holiday_id <>", value, "holidayId");
            return (Criteria) this;
        }

        public Criteria andHolidayIdGreaterThan(String value) {
            addCriterion("holiday_id >", value, "holidayId");
            return (Criteria) this;
        }

        public Criteria andHolidayIdGreaterThanOrEqualTo(String value) {
            addCriterion("holiday_id >=", value, "holidayId");
            return (Criteria) this;
        }

        public Criteria andHolidayIdLessThan(String value) {
            addCriterion("holiday_id <", value, "holidayId");
            return (Criteria) this;
        }

        public Criteria andHolidayIdLessThanOrEqualTo(String value) {
            addCriterion("holiday_id <=", value, "holidayId");
            return (Criteria) this;
        }

        public Criteria andHolidayIdLike(String value) {
            addCriterion("holiday_id like", value, "holidayId");
            return (Criteria) this;
        }

        public Criteria andHolidayIdNotLike(String value) {
            addCriterion("holiday_id not like", value, "holidayId");
            return (Criteria) this;
        }

        public Criteria andHolidayIdIn(List<String> values) {
            addCriterion("holiday_id in", values, "holidayId");
            return (Criteria) this;
        }

        public Criteria andHolidayIdNotIn(List<String> values) {
            addCriterion("holiday_id not in", values, "holidayId");
            return (Criteria) this;
        }

        public Criteria andHolidayIdBetween(String value1, String value2) {
            addCriterion("holiday_id between", value1, value2, "holidayId");
            return (Criteria) this;
        }

        public Criteria andHolidayIdNotBetween(String value1, String value2) {
            addCriterion("holiday_id not between", value1, value2, "holidayId");
            return (Criteria) this;
        }

        public Criteria andDateTypeIsNull() {
            addCriterion("date_type is null");
            return (Criteria) this;
        }

        public Criteria andDateTypeIsNotNull() {
            addCriterion("date_type is not null");
            return (Criteria) this;
        }

        public Criteria andDateTypeEqualTo(String value) {
            addCriterion("date_type =", value, "dateType");
            return (Criteria) this;
        }

        public Criteria andDateTypeNotEqualTo(String value) {
            addCriterion("date_type <>", value, "dateType");
            return (Criteria) this;
        }

        public Criteria andDateTypeGreaterThan(String value) {
            addCriterion("date_type >", value, "dateType");
            return (Criteria) this;
        }

        public Criteria andDateTypeGreaterThanOrEqualTo(String value) {
            addCriterion("date_type >=", value, "dateType");
            return (Criteria) this;
        }

        public Criteria andDateTypeLessThan(String value) {
            addCriterion("date_type <", value, "dateType");
            return (Criteria) this;
        }

        public Criteria andDateTypeLessThanOrEqualTo(String value) {
            addCriterion("date_type <=", value, "dateType");
            return (Criteria) this;
        }

        public Criteria andDateTypeLike(String value) {
            addCriterion("date_type like", value, "dateType");
            return (Criteria) this;
        }

        public Criteria andDateTypeNotLike(String value) {
            addCriterion("date_type not like", value, "dateType");
            return (Criteria) this;
        }

        public Criteria andDateTypeIn(List<String> values) {
            addCriterion("date_type in", values, "dateType");
            return (Criteria) this;
        }

        public Criteria andDateTypeNotIn(List<String> values) {
            addCriterion("date_type not in", values, "dateType");
            return (Criteria) this;
        }

        public Criteria andDateTypeBetween(String value1, String value2) {
            addCriterion("date_type between", value1, value2, "dateType");
            return (Criteria) this;
        }

        public Criteria andDateTypeNotBetween(String value1, String value2) {
            addCriterion("date_type not between", value1, value2, "dateType");
            return (Criteria) this;
        }

        public Criteria andDayofweekIsNull() {
            addCriterion("dayofweek is null");
            return (Criteria) this;
        }

        public Criteria andDayofweekIsNotNull() {
            addCriterion("dayofweek is not null");
            return (Criteria) this;
        }

        public Criteria andDayofweekEqualTo(String value) {
            addCriterion("dayofweek =", value, "dayofweek");
            return (Criteria) this;
        }

        public Criteria andDayofweekNotEqualTo(String value) {
            addCriterion("dayofweek <>", value, "dayofweek");
            return (Criteria) this;
        }

        public Criteria andDayofweekGreaterThan(String value) {
            addCriterion("dayofweek >", value, "dayofweek");
            return (Criteria) this;
        }

        public Criteria andDayofweekGreaterThanOrEqualTo(String value) {
            addCriterion("dayofweek >=", value, "dayofweek");
            return (Criteria) this;
        }

        public Criteria andDayofweekLessThan(String value) {
            addCriterion("dayofweek <", value, "dayofweek");
            return (Criteria) this;
        }

        public Criteria andDayofweekLessThanOrEqualTo(String value) {
            addCriterion("dayofweek <=", value, "dayofweek");
            return (Criteria) this;
        }

        public Criteria andDayofweekLike(String value) {
            addCriterion("dayofweek like", value, "dayofweek");
            return (Criteria) this;
        }

        public Criteria andDayofweekNotLike(String value) {
            addCriterion("dayofweek not like", value, "dayofweek");
            return (Criteria) this;
        }

        public Criteria andDayofweekIn(List<String> values) {
            addCriterion("dayofweek in", values, "dayofweek");
            return (Criteria) this;
        }

        public Criteria andDayofweekNotIn(List<String> values) {
            addCriterion("dayofweek not in", values, "dayofweek");
            return (Criteria) this;
        }

        public Criteria andDayofweekBetween(String value1, String value2) {
            addCriterion("dayofweek between", value1, value2, "dayofweek");
            return (Criteria) this;
        }

        public Criteria andDayofweekNotBetween(String value1, String value2) {
            addCriterion("dayofweek not between", value1, value2, "dayofweek");
            return (Criteria) this;
        }

        public Criteria andWeekNumIsNull() {
            addCriterion("week_num is null");
            return (Criteria) this;
        }

        public Criteria andWeekNumIsNotNull() {
            addCriterion("week_num is not null");
            return (Criteria) this;
        }

        public Criteria andWeekNumEqualTo(Integer value) {
            addCriterion("week_num =", value, "weekNum");
            return (Criteria) this;
        }

        public Criteria andWeekNumNotEqualTo(Integer value) {
            addCriterion("week_num <>", value, "weekNum");
            return (Criteria) this;
        }

        public Criteria andWeekNumGreaterThan(Integer value) {
            addCriterion("week_num >", value, "weekNum");
            return (Criteria) this;
        }

        public Criteria andWeekNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("week_num >=", value, "weekNum");
            return (Criteria) this;
        }

        public Criteria andWeekNumLessThan(Integer value) {
            addCriterion("week_num <", value, "weekNum");
            return (Criteria) this;
        }

        public Criteria andWeekNumLessThanOrEqualTo(Integer value) {
            addCriterion("week_num <=", value, "weekNum");
            return (Criteria) this;
        }

        public Criteria andWeekNumIn(List<Integer> values) {
            addCriterion("week_num in", values, "weekNum");
            return (Criteria) this;
        }

        public Criteria andWeekNumNotIn(List<Integer> values) {
            addCriterion("week_num not in", values, "weekNum");
            return (Criteria) this;
        }

        public Criteria andWeekNumBetween(Integer value1, Integer value2) {
            addCriterion("week_num between", value1, value2, "weekNum");
            return (Criteria) this;
        }

        public Criteria andWeekNumNotBetween(Integer value1, Integer value2) {
            addCriterion("week_num not between", value1, value2, "weekNum");
            return (Criteria) this;
        }

        public Criteria andWeatherIsNull() {
            addCriterion("weather is null");
            return (Criteria) this;
        }

        public Criteria andWeatherIsNotNull() {
            addCriterion("weather is not null");
            return (Criteria) this;
        }

        public Criteria andWeatherEqualTo(String value) {
            addCriterion("weather =", value, "weather");
            return (Criteria) this;
        }

        public Criteria andWeatherNotEqualTo(String value) {
            addCriterion("weather <>", value, "weather");
            return (Criteria) this;
        }

        public Criteria andWeatherGreaterThan(String value) {
            addCriterion("weather >", value, "weather");
            return (Criteria) this;
        }

        public Criteria andWeatherGreaterThanOrEqualTo(String value) {
            addCriterion("weather >=", value, "weather");
            return (Criteria) this;
        }

        public Criteria andWeatherLessThan(String value) {
            addCriterion("weather <", value, "weather");
            return (Criteria) this;
        }

        public Criteria andWeatherLessThanOrEqualTo(String value) {
            addCriterion("weather <=", value, "weather");
            return (Criteria) this;
        }

        public Criteria andWeatherLike(String value) {
            addCriterion("weather like", value, "weather");
            return (Criteria) this;
        }

        public Criteria andWeatherNotLike(String value) {
            addCriterion("weather not like", value, "weather");
            return (Criteria) this;
        }

        public Criteria andWeatherIn(List<String> values) {
            addCriterion("weather in", values, "weather");
            return (Criteria) this;
        }

        public Criteria andWeatherNotIn(List<String> values) {
            addCriterion("weather not in", values, "weather");
            return (Criteria) this;
        }

        public Criteria andWeatherBetween(String value1, String value2) {
            addCriterion("weather between", value1, value2, "weather");
            return (Criteria) this;
        }

        public Criteria andWeatherNotBetween(String value1, String value2) {
            addCriterion("weather not between", value1, value2, "weather");
            return (Criteria) this;
        }

        public Criteria andCustomerVolumnIsNull() {
            addCriterion("customer_volumn is null");
            return (Criteria) this;
        }

        public Criteria andCustomerVolumnIsNotNull() {
            addCriterion("customer_volumn is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerVolumnEqualTo(Integer value) {
            addCriterion("customer_volumn =", value, "customerVolumn");
            return (Criteria) this;
        }

        public Criteria andCustomerVolumnNotEqualTo(Integer value) {
            addCriterion("customer_volumn <>", value, "customerVolumn");
            return (Criteria) this;
        }

        public Criteria andCustomerVolumnGreaterThan(Integer value) {
            addCriterion("customer_volumn >", value, "customerVolumn");
            return (Criteria) this;
        }

        public Criteria andCustomerVolumnGreaterThanOrEqualTo(Integer value) {
            addCriterion("customer_volumn >=", value, "customerVolumn");
            return (Criteria) this;
        }

        public Criteria andCustomerVolumnLessThan(Integer value) {
            addCriterion("customer_volumn <", value, "customerVolumn");
            return (Criteria) this;
        }

        public Criteria andCustomerVolumnLessThanOrEqualTo(Integer value) {
            addCriterion("customer_volumn <=", value, "customerVolumn");
            return (Criteria) this;
        }

        public Criteria andCustomerVolumnIn(List<Integer> values) {
            addCriterion("customer_volumn in", values, "customerVolumn");
            return (Criteria) this;
        }

        public Criteria andCustomerVolumnNotIn(List<Integer> values) {
            addCriterion("customer_volumn not in", values, "customerVolumn");
            return (Criteria) this;
        }

        public Criteria andCustomerVolumnBetween(Integer value1, Integer value2) {
            addCriterion("customer_volumn between", value1, value2, "customerVolumn");
            return (Criteria) this;
        }

        public Criteria andCustomerVolumnNotBetween(Integer value1, Integer value2) {
            addCriterion("customer_volumn not between", value1, value2, "customerVolumn");
            return (Criteria) this;
        }

        public Criteria andCreationDateIsNull() {
            addCriterion("creation_date is null");
            return (Criteria) this;
        }

        public Criteria andCreationDateIsNotNull() {
            addCriterion("creation_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreationDateEqualTo(Date value) {
            addCriterion("creation_date =", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateNotEqualTo(Date value) {
            addCriterion("creation_date <>", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateGreaterThan(Date value) {
            addCriterion("creation_date >", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateGreaterThanOrEqualTo(Date value) {
            addCriterion("creation_date >=", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateLessThan(Date value) {
            addCriterion("creation_date <", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateLessThanOrEqualTo(Date value) {
            addCriterion("creation_date <=", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateIn(List<Date> values) {
            addCriterion("creation_date in", values, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateNotIn(List<Date> values) {
            addCriterion("creation_date not in", values, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateBetween(Date value1, Date value2) {
            addCriterion("creation_date between", value1, value2, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateNotBetween(Date value1, Date value2) {
            addCriterion("creation_date not between", value1, value2, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("created_by is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("created_by is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(String value) {
            addCriterion("created_by =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(String value) {
            addCriterion("created_by <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(String value) {
            addCriterion("created_by >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(String value) {
            addCriterion("created_by >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(String value) {
            addCriterion("created_by <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(String value) {
            addCriterion("created_by <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLike(String value) {
            addCriterion("created_by like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotLike(String value) {
            addCriterion("created_by not like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<String> values) {
            addCriterion("created_by in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<String> values) {
            addCriterion("created_by not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(String value1, String value2) {
            addCriterion("created_by between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(String value1, String value2) {
            addCriterion("created_by not between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNull() {
            addCriterion("update_by is null");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNotNull() {
            addCriterion("update_by is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateByEqualTo(String value) {
            addCriterion("update_by =", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotEqualTo(String value) {
            addCriterion("update_by <>", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThan(String value) {
            addCriterion("update_by >", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThanOrEqualTo(String value) {
            addCriterion("update_by >=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThan(String value) {
            addCriterion("update_by <", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThanOrEqualTo(String value) {
            addCriterion("update_by <=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLike(String value) {
            addCriterion("update_by like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotLike(String value) {
            addCriterion("update_by not like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByIn(List<String> values) {
            addCriterion("update_by in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotIn(List<String> values) {
            addCriterion("update_by not in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByBetween(String value1, String value2) {
            addCriterion("update_by between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotBetween(String value1, String value2) {
            addCriterion("update_by not between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andIsAliveIsNull() {
            addCriterion("is_alive is null");
            return (Criteria) this;
        }

        public Criteria andIsAliveIsNotNull() {
            addCriterion("is_alive is not null");
            return (Criteria) this;
        }

        public Criteria andIsAliveEqualTo(Boolean value) {
            addCriterion("is_alive =", value, "isAlive");
            return (Criteria) this;
        }

        public Criteria andIsAliveNotEqualTo(Boolean value) {
            addCriterion("is_alive <>", value, "isAlive");
            return (Criteria) this;
        }

        public Criteria andIsAliveGreaterThan(Boolean value) {
            addCriterion("is_alive >", value, "isAlive");
            return (Criteria) this;
        }

        public Criteria andIsAliveGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_alive >=", value, "isAlive");
            return (Criteria) this;
        }

        public Criteria andIsAliveLessThan(Boolean value) {
            addCriterion("is_alive <", value, "isAlive");
            return (Criteria) this;
        }

        public Criteria andIsAliveLessThanOrEqualTo(Boolean value) {
            addCriterion("is_alive <=", value, "isAlive");
            return (Criteria) this;
        }

        public Criteria andIsAliveIn(List<Boolean> values) {
            addCriterion("is_alive in", values, "isAlive");
            return (Criteria) this;
        }

        public Criteria andIsAliveNotIn(List<Boolean> values) {
            addCriterion("is_alive not in", values, "isAlive");
            return (Criteria) this;
        }

        public Criteria andIsAliveBetween(Boolean value1, Boolean value2) {
            addCriterion("is_alive between", value1, value2, "isAlive");
            return (Criteria) this;
        }

        public Criteria andIsAliveNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_alive not between", value1, value2, "isAlive");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table e_brand_daily_achievement
     *
     * @mbg.generated do_not_delete_during_merge Thu Nov 24 17:04:55 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table e_brand_daily_achievement
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}