package net.ray.web.ees.db.eo;

import java.util.Date;

public class Floors {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_floors.id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_floors.floor_number
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String floorNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_floors.creation_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Date creationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_floors.created_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_floors.update_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_floors.updated_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_floors.is_alive
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Boolean isAlive;
    private String floorNameEn;
    private Float floorArea;
    private String floorDef;

    public String getFloorNameEn() {
        return floorNameEn;
    }

    public void setFloorNameEn(String floorNameEn) {
        this.floorNameEn = floorNameEn;
    }

    public Float getFloorArea() {
        return floorArea;
    }

    public void setFloorArea(Float floorArea) {
        this.floorArea = floorArea;
    }

    public String getFloorDef() {
        return floorDef;
    }

    public void setFloorDef(String floorDef) {
        this.floorDef = floorDef;
    }
    
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_floors.id
     *
     * @return the value of e_floors.id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_floors.id
     *
     * @param id the value for e_floors.id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_floors.floor_number
     *
     * @return the value of e_floors.floor_number
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getFloorNumber() {
        return floorNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_floors.floor_number
     *
     * @param floorNumber the value for e_floors.floor_number
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setFloorNumber(String floorNumber) {
        this.floorNumber = floorNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_floors.creation_date
     *
     * @return the value of e_floors.creation_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_floors.creation_date
     *
     * @param creationDate the value for e_floors.creation_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_floors.created_by
     *
     * @return the value of e_floors.created_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_floors.created_by
     *
     * @param createdBy the value for e_floors.created_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_floors.update_date
     *
     * @return the value of e_floors.update_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_floors.update_date
     *
     * @param updateDate the value for e_floors.update_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_floors.updated_by
     *
     * @return the value of e_floors.updated_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_floors.updated_by
     *
     * @param updatedBy the value for e_floors.updated_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_floors.is_alive
     *
     * @return the value of e_floors.is_alive
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Boolean getIsAlive() {
        return isAlive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_floors.is_alive
     *
     * @param isAlive the value for e_floors.is_alive
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setIsAlive(Boolean isAlive) {
        this.isAlive = isAlive;
    }
}