package net.ray.web.ees.db.eo;

import java.util.Date;

public class MallBase {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_mall_base.id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_mall_base.pro_name
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String proName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_mall_base.pro_area
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Float proArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_mall_base.pro_open_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Date proOpenDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_mall_base.pro_rent_area
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Float proRentArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_mall_base.pro_brand_num
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Integer proBrandNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_mall_base.floor_num
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Integer floorNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_mall_base.brand_class_number
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Integer brandClassNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_mall_base.brand_type1_num
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Integer brandType1Num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_mall_base.brand_type2_num
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Integer brandType2Num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_mall_base.creation_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Date creationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_mall_base.created_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_mall_base.update_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_mall_base.updated_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_mall_base.is_alive
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Boolean isAlive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_mall_base.id
     *
     * @return the value of e_mall_base.id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_mall_base.id
     *
     * @param id the value for e_mall_base.id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_mall_base.pro_name
     *
     * @return the value of e_mall_base.pro_name
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getProName() {
        return proName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_mall_base.pro_name
     *
     * @param proName the value for e_mall_base.pro_name
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setProName(String proName) {
        this.proName = proName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_mall_base.pro_area
     *
     * @return the value of e_mall_base.pro_area
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Float getProArea() {
        return proArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_mall_base.pro_area
     *
     * @param proArea the value for e_mall_base.pro_area
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setProArea(Float proArea) {
        this.proArea = proArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_mall_base.pro_open_date
     *
     * @return the value of e_mall_base.pro_open_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Date getProOpenDate() {
        return proOpenDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_mall_base.pro_open_date
     *
     * @param proOpenDate the value for e_mall_base.pro_open_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setProOpenDate(Date proOpenDate) {
        this.proOpenDate = proOpenDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_mall_base.pro_rent_area
     *
     * @return the value of e_mall_base.pro_rent_area
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Float getProRentArea() {
        return proRentArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_mall_base.pro_rent_area
     *
     * @param proRentArea the value for e_mall_base.pro_rent_area
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setProRentArea(Float proRentArea) {
        this.proRentArea = proRentArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_mall_base.pro_brand_num
     *
     * @return the value of e_mall_base.pro_brand_num
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Integer getProBrandNum() {
        return proBrandNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_mall_base.pro_brand_num
     *
     * @param proBrandNum the value for e_mall_base.pro_brand_num
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setProBrandNum(Integer proBrandNum) {
        this.proBrandNum = proBrandNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_mall_base.floor_num
     *
     * @return the value of e_mall_base.floor_num
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Integer getFloorNum() {
        return floorNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_mall_base.floor_num
     *
     * @param floorNum the value for e_mall_base.floor_num
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setFloorNum(Integer floorNum) {
        this.floorNum = floorNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_mall_base.brand_class_number
     *
     * @return the value of e_mall_base.brand_class_number
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Integer getBrandClassNumber() {
        return brandClassNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_mall_base.brand_class_number
     *
     * @param brandClassNumber the value for e_mall_base.brand_class_number
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setBrandClassNumber(Integer brandClassNumber) {
        this.brandClassNumber = brandClassNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_mall_base.brand_type1_num
     *
     * @return the value of e_mall_base.brand_type1_num
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Integer getBrandType1Num() {
        return brandType1Num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_mall_base.brand_type1_num
     *
     * @param brandType1Num the value for e_mall_base.brand_type1_num
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setBrandType1Num(Integer brandType1Num) {
        this.brandType1Num = brandType1Num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_mall_base.brand_type2_num
     *
     * @return the value of e_mall_base.brand_type2_num
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Integer getBrandType2Num() {
        return brandType2Num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_mall_base.brand_type2_num
     *
     * @param brandType2Num the value for e_mall_base.brand_type2_num
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setBrandType2Num(Integer brandType2Num) {
        this.brandType2Num = brandType2Num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_mall_base.creation_date
     *
     * @return the value of e_mall_base.creation_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_mall_base.creation_date
     *
     * @param creationDate the value for e_mall_base.creation_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_mall_base.created_by
     *
     * @return the value of e_mall_base.created_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_mall_base.created_by
     *
     * @param createdBy the value for e_mall_base.created_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_mall_base.update_date
     *
     * @return the value of e_mall_base.update_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_mall_base.update_date
     *
     * @param updateDate the value for e_mall_base.update_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_mall_base.updated_by
     *
     * @return the value of e_mall_base.updated_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_mall_base.updated_by
     *
     * @param updatedBy the value for e_mall_base.updated_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_mall_base.is_alive
     *
     * @return the value of e_mall_base.is_alive
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Boolean getIsAlive() {
        return isAlive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_mall_base.is_alive
     *
     * @param isAlive the value for e_mall_base.is_alive
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setIsAlive(Boolean isAlive) {
        this.isAlive = isAlive;
    }
}