package net.ray.web.ees.db.eo;

import java.util.Date;

public class MallFloor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_mall_floor.id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_mall_floor.mall_id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String mallId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_mall_floor.floor_id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String floorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_mall_floor.floor_brand_number
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Integer floorBrandNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_mall_floor.floor_area
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Float floorArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_mall_floor.creation_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Date creationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_mall_floor.created_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_mall_floor.update_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_mall_floor.updated_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_mall_floor.is_alive
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Boolean isAlive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_mall_floor.id
     *
     * @return the value of e_mall_floor.id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_mall_floor.id
     *
     * @param id the value for e_mall_floor.id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_mall_floor.mall_id
     *
     * @return the value of e_mall_floor.mall_id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getMallId() {
        return mallId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_mall_floor.mall_id
     *
     * @param mallId the value for e_mall_floor.mall_id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setMallId(String mallId) {
        this.mallId = mallId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_mall_floor.floor_id
     *
     * @return the value of e_mall_floor.floor_id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getFloorId() {
        return floorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_mall_floor.floor_id
     *
     * @param floorId the value for e_mall_floor.floor_id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setFloorId(String floorId) {
        this.floorId = floorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_mall_floor.floor_brand_number
     *
     * @return the value of e_mall_floor.floor_brand_number
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Integer getFloorBrandNumber() {
        return floorBrandNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_mall_floor.floor_brand_number
     *
     * @param floorBrandNumber the value for e_mall_floor.floor_brand_number
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setFloorBrandNumber(Integer floorBrandNumber) {
        this.floorBrandNumber = floorBrandNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_mall_floor.floor_area
     *
     * @return the value of e_mall_floor.floor_area
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Float getFloorArea() {
        return floorArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_mall_floor.floor_area
     *
     * @param floorArea the value for e_mall_floor.floor_area
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setFloorArea(Float floorArea) {
        this.floorArea = floorArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_mall_floor.creation_date
     *
     * @return the value of e_mall_floor.creation_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_mall_floor.creation_date
     *
     * @param creationDate the value for e_mall_floor.creation_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_mall_floor.created_by
     *
     * @return the value of e_mall_floor.created_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_mall_floor.created_by
     *
     * @param createdBy the value for e_mall_floor.created_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_mall_floor.update_date
     *
     * @return the value of e_mall_floor.update_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_mall_floor.update_date
     *
     * @param updateDate the value for e_mall_floor.update_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_mall_floor.updated_by
     *
     * @return the value of e_mall_floor.updated_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_mall_floor.updated_by
     *
     * @param updatedBy the value for e_mall_floor.updated_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_mall_floor.is_alive
     *
     * @return the value of e_mall_floor.is_alive
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Boolean getIsAlive() {
        return isAlive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_mall_floor.is_alive
     *
     * @param isAlive the value for e_mall_floor.is_alive
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setIsAlive(Boolean isAlive) {
        this.isAlive = isAlive;
    }
}