package net.ray.web.ees.db.eo;

import java.util.Date;

public class Menus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_menus.id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_menus.parent_id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_menus.root_id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Integer rootId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_menus.menu_name
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String menuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_menus.menu_href
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String menuHref;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_menus.isLeaf
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Boolean isleaf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_menus.creation_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Date creationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_menus.created_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_menus.update_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_menus.update_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_menus.isAlive
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Boolean isalive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_menus.id
     *
     * @return the value of e_menus.id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_menus.id
     *
     * @param id the value for e_menus.id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_menus.parent_id
     *
     * @return the value of e_menus.parent_id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_menus.parent_id
     *
     * @param parentId the value for e_menus.parent_id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_menus.root_id
     *
     * @return the value of e_menus.root_id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Integer getRootId() {
        return rootId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_menus.root_id
     *
     * @param rootId the value for e_menus.root_id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setRootId(Integer rootId) {
        this.rootId = rootId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_menus.menu_name
     *
     * @return the value of e_menus.menu_name
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_menus.menu_name
     *
     * @param menuName the value for e_menus.menu_name
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_menus.menu_href
     *
     * @return the value of e_menus.menu_href
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getMenuHref() {
        return menuHref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_menus.menu_href
     *
     * @param menuHref the value for e_menus.menu_href
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setMenuHref(String menuHref) {
        this.menuHref = menuHref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_menus.isLeaf
     *
     * @return the value of e_menus.isLeaf
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Boolean getIsleaf() {
        return isleaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_menus.isLeaf
     *
     * @param isleaf the value for e_menus.isLeaf
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setIsleaf(Boolean isleaf) {
        this.isleaf = isleaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_menus.creation_date
     *
     * @return the value of e_menus.creation_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_menus.creation_date
     *
     * @param creationDate the value for e_menus.creation_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_menus.created_by
     *
     * @return the value of e_menus.created_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_menus.created_by
     *
     * @param createdBy the value for e_menus.created_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_menus.update_date
     *
     * @return the value of e_menus.update_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_menus.update_date
     *
     * @param updateDate the value for e_menus.update_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_menus.update_by
     *
     * @return the value of e_menus.update_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_menus.update_by
     *
     * @param updateBy the value for e_menus.update_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_menus.isAlive
     *
     * @return the value of e_menus.isAlive
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Boolean getIsalive() {
        return isalive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_menus.isAlive
     *
     * @param isalive the value for e_menus.isAlive
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setIsalive(Boolean isalive) {
        this.isalive = isalive;
    }
}