package net.ray.web.ees.db.eo;

import java.util.Date;

public class Person {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_person.id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_person.person_number
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String personNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_person.person_name
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String personName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_person.login_name
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_person.password
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_person.sex
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Boolean sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_person.age
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_person.birthday
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_person.image_path
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String imagePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_person.entrant_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Date entrantDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_person.mac_address
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String macAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_person.home_address
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String homeAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_person.remark
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_person.creation_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Date creationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_person.tel_number
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String telNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_person.cell_phone
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String cellPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_person.created_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_person.update_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_person.updated_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_person.is_alive
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Boolean isAlive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_person.email
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String email;
    
    private String jobTitle;
    private String authority;
    

    public String getJobTitle() {
		return jobTitle;
	}

	public void setJobTitle(String jobTitle) {
		this.jobTitle = jobTitle;
	}

	public String getAuthority() {
		return authority;
	}

	public void setAuthority(String authority) {
		this.authority = authority;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_person.id
     *
     * @return the value of e_person.id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_person.id
     *
     * @param id the value for e_person.id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_person.person_number
     *
     * @return the value of e_person.person_number
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getPersonNumber() {
        return personNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_person.person_number
     *
     * @param personNumber the value for e_person.person_number
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setPersonNumber(String personNumber) {
        this.personNumber = personNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_person.person_name
     *
     * @return the value of e_person.person_name
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getPersonName() {
        return personName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_person.person_name
     *
     * @param personName the value for e_person.person_name
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setPersonName(String personName) {
        this.personName = personName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_person.login_name
     *
     * @return the value of e_person.login_name
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_person.login_name
     *
     * @param loginName the value for e_person.login_name
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_person.password
     *
     * @return the value of e_person.password
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_person.password
     *
     * @param password the value for e_person.password
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_person.sex
     *
     * @return the value of e_person.sex
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Boolean getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_person.sex
     *
     * @param sex the value for e_person.sex
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setSex(Boolean sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_person.age
     *
     * @return the value of e_person.age
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_person.age
     *
     * @param age the value for e_person.age
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_person.birthday
     *
     * @return the value of e_person.birthday
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_person.birthday
     *
     * @param birthday the value for e_person.birthday
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_person.image_path
     *
     * @return the value of e_person.image_path
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getImagePath() {
        return imagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_person.image_path
     *
     * @param imagePath the value for e_person.image_path
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setImagePath(String imagePath) {
        this.imagePath = imagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_person.entrant_date
     *
     * @return the value of e_person.entrant_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Date getEntrantDate() {
        return entrantDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_person.entrant_date
     *
     * @param entrantDate the value for e_person.entrant_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setEntrantDate(Date entrantDate) {
        this.entrantDate = entrantDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_person.mac_address
     *
     * @return the value of e_person.mac_address
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getMacAddress() {
        return macAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_person.mac_address
     *
     * @param macAddress the value for e_person.mac_address
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setMacAddress(String macAddress) {
        this.macAddress = macAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_person.home_address
     *
     * @return the value of e_person.home_address
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getHomeAddress() {
        return homeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_person.home_address
     *
     * @param homeAddress the value for e_person.home_address
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setHomeAddress(String homeAddress) {
        this.homeAddress = homeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_person.remark
     *
     * @return the value of e_person.remark
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_person.remark
     *
     * @param remark the value for e_person.remark
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_person.creation_date
     *
     * @return the value of e_person.creation_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_person.creation_date
     *
     * @param creationDate the value for e_person.creation_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_person.tel_number
     *
     * @return the value of e_person.tel_number
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getTelNumber() {
        return telNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_person.tel_number
     *
     * @param telNumber the value for e_person.tel_number
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setTelNumber(String telNumber) {
        this.telNumber = telNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_person.cell_phone
     *
     * @return the value of e_person.cell_phone
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getCellPhone() {
        return cellPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_person.cell_phone
     *
     * @param cellPhone the value for e_person.cell_phone
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setCellPhone(String cellPhone) {
        this.cellPhone = cellPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_person.created_by
     *
     * @return the value of e_person.created_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_person.created_by
     *
     * @param createdBy the value for e_person.created_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_person.update_date
     *
     * @return the value of e_person.update_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_person.update_date
     *
     * @param updateDate the value for e_person.update_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_person.updated_by
     *
     * @return the value of e_person.updated_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_person.updated_by
     *
     * @param updatedBy the value for e_person.updated_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_person.is_alive
     *
     * @return the value of e_person.is_alive
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Boolean getIsAlive() {
        return isAlive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_person.is_alive
     *
     * @param isAlive the value for e_person.is_alive
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setIsAlive(Boolean isAlive) {
        this.isAlive = isAlive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_person.email
     *
     * @return the value of e_person.email
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_person.email
     *
     * @param email the value for e_person.email
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setEmail(String email) {
        this.email = email;
    }
}