package net.ray.web.ees.db.eo;

import java.util.Date;

public class RentType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_rent_type.id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_rent_type.rent_name
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String rentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_rent_type.rent_attr1
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String rentAttr1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_rent_type.rent_attr2
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String rentAttr2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_rent_type.rent_attr3
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String rentAttr3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_rent_type.rent_attr4
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String rentAttr4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_rent_type.rent_attr5
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String rentAttr5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_rent_type.rent_attr6
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String rentAttr6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_rent_type.creation_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Date creationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_rent_type.created_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_rent_type.update_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_rent_type.update_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_rent_type.is_alive
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Boolean isAlive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_rent_type.id
     *
     * @return the value of e_rent_type.id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_rent_type.id
     *
     * @param id the value for e_rent_type.id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_rent_type.rent_name
     *
     * @return the value of e_rent_type.rent_name
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getRentName() {
        return rentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_rent_type.rent_name
     *
     * @param rentName the value for e_rent_type.rent_name
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setRentName(String rentName) {
        this.rentName = rentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_rent_type.rent_attr1
     *
     * @return the value of e_rent_type.rent_attr1
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getRentAttr1() {
        return rentAttr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_rent_type.rent_attr1
     *
     * @param rentAttr1 the value for e_rent_type.rent_attr1
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setRentAttr1(String rentAttr1) {
        this.rentAttr1 = rentAttr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_rent_type.rent_attr2
     *
     * @return the value of e_rent_type.rent_attr2
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getRentAttr2() {
        return rentAttr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_rent_type.rent_attr2
     *
     * @param rentAttr2 the value for e_rent_type.rent_attr2
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setRentAttr2(String rentAttr2) {
        this.rentAttr2 = rentAttr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_rent_type.rent_attr3
     *
     * @return the value of e_rent_type.rent_attr3
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getRentAttr3() {
        return rentAttr3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_rent_type.rent_attr3
     *
     * @param rentAttr3 the value for e_rent_type.rent_attr3
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setRentAttr3(String rentAttr3) {
        this.rentAttr3 = rentAttr3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_rent_type.rent_attr4
     *
     * @return the value of e_rent_type.rent_attr4
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getRentAttr4() {
        return rentAttr4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_rent_type.rent_attr4
     *
     * @param rentAttr4 the value for e_rent_type.rent_attr4
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setRentAttr4(String rentAttr4) {
        this.rentAttr4 = rentAttr4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_rent_type.rent_attr5
     *
     * @return the value of e_rent_type.rent_attr5
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getRentAttr5() {
        return rentAttr5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_rent_type.rent_attr5
     *
     * @param rentAttr5 the value for e_rent_type.rent_attr5
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setRentAttr5(String rentAttr5) {
        this.rentAttr5 = rentAttr5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_rent_type.rent_attr6
     *
     * @return the value of e_rent_type.rent_attr6
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getRentAttr6() {
        return rentAttr6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_rent_type.rent_attr6
     *
     * @param rentAttr6 the value for e_rent_type.rent_attr6
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setRentAttr6(String rentAttr6) {
        this.rentAttr6 = rentAttr6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_rent_type.creation_date
     *
     * @return the value of e_rent_type.creation_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_rent_type.creation_date
     *
     * @param creationDate the value for e_rent_type.creation_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_rent_type.created_by
     *
     * @return the value of e_rent_type.created_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_rent_type.created_by
     *
     * @param createdBy the value for e_rent_type.created_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_rent_type.update_date
     *
     * @return the value of e_rent_type.update_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_rent_type.update_date
     *
     * @param updateDate the value for e_rent_type.update_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_rent_type.update_by
     *
     * @return the value of e_rent_type.update_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_rent_type.update_by
     *
     * @param updateBy the value for e_rent_type.update_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_rent_type.is_alive
     *
     * @return the value of e_rent_type.is_alive
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Boolean getIsAlive() {
        return isAlive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_rent_type.is_alive
     *
     * @param isAlive the value for e_rent_type.is_alive
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setIsAlive(Boolean isAlive) {
        this.isAlive = isAlive;
    }
}