package net.ray.web.ees.db.eo;

import java.util.Date;

public class TradeMonthlyAchievement {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_monthly_achievement.id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_monthly_achievement.trade_id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Integer tradeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_monthly_achievement.mall_id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Integer mallId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_monthly_achievement.sale_month
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Date saleMonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_monthly_achievement.sales_amount
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Float salesAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_monthly_achievement.sales_volume
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Integer salesVolume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_monthly_achievement.sales_times
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Integer salesTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_monthly_achievement.m_rent
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Float mRent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_monthly_achievement.m_property
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Float mProperty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_monthly_achievement.m_other_charge1
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Float mOtherCharge1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_monthly_achievement.m_other_charge2
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Float mOtherCharge2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_monthly_achievement.m_other_charge3
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Float mOtherCharge3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_monthly_achievement.m_fixed_charge1
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Float mFixedCharge1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_monthly_achievement.m_fixed_charge2
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Float mFixedCharge2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_monthly_achievement.m_fixed_charge3
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Float mFixedCharge3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_monthly_achievement.update_dates
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Date updateDates;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_monthly_achievement.customer_volume
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Integer customerVolume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_monthly_achievement.car_volume
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Integer carVolume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_monthly_achievement.creation_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Date creationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_monthly_achievement.created_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_monthly_achievement.update_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_monthly_achievement.updated_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_monthly_achievement.is_alive
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Boolean isAlive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_monthly_achievement.id
     *
     * @return the value of e_trade_monthly_achievement.id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_monthly_achievement.id
     *
     * @param id the value for e_trade_monthly_achievement.id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_monthly_achievement.trade_id
     *
     * @return the value of e_trade_monthly_achievement.trade_id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Integer getTradeId() {
        return tradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_monthly_achievement.trade_id
     *
     * @param tradeId the value for e_trade_monthly_achievement.trade_id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setTradeId(Integer tradeId) {
        this.tradeId = tradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_monthly_achievement.mall_id
     *
     * @return the value of e_trade_monthly_achievement.mall_id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Integer getMallId() {
        return mallId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_monthly_achievement.mall_id
     *
     * @param mallId the value for e_trade_monthly_achievement.mall_id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setMallId(Integer mallId) {
        this.mallId = mallId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_monthly_achievement.sale_month
     *
     * @return the value of e_trade_monthly_achievement.sale_month
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Date getSaleMonth() {
        return saleMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_monthly_achievement.sale_month
     *
     * @param saleMonth the value for e_trade_monthly_achievement.sale_month
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setSaleMonth(Date saleMonth) {
        this.saleMonth = saleMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_monthly_achievement.sales_amount
     *
     * @return the value of e_trade_monthly_achievement.sales_amount
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Float getSalesAmount() {
        return salesAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_monthly_achievement.sales_amount
     *
     * @param salesAmount the value for e_trade_monthly_achievement.sales_amount
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setSalesAmount(Float salesAmount) {
        this.salesAmount = salesAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_monthly_achievement.sales_volume
     *
     * @return the value of e_trade_monthly_achievement.sales_volume
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Integer getSalesVolume() {
        return salesVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_monthly_achievement.sales_volume
     *
     * @param salesVolume the value for e_trade_monthly_achievement.sales_volume
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setSalesVolume(Integer salesVolume) {
        this.salesVolume = salesVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_monthly_achievement.sales_times
     *
     * @return the value of e_trade_monthly_achievement.sales_times
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Integer getSalesTimes() {
        return salesTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_monthly_achievement.sales_times
     *
     * @param salesTimes the value for e_trade_monthly_achievement.sales_times
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setSalesTimes(Integer salesTimes) {
        this.salesTimes = salesTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_monthly_achievement.m_rent
     *
     * @return the value of e_trade_monthly_achievement.m_rent
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Float getmRent() {
        return mRent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_monthly_achievement.m_rent
     *
     * @param mRent the value for e_trade_monthly_achievement.m_rent
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setmRent(Float mRent) {
        this.mRent = mRent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_monthly_achievement.m_property
     *
     * @return the value of e_trade_monthly_achievement.m_property
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Float getmProperty() {
        return mProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_monthly_achievement.m_property
     *
     * @param mProperty the value for e_trade_monthly_achievement.m_property
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setmProperty(Float mProperty) {
        this.mProperty = mProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_monthly_achievement.m_other_charge1
     *
     * @return the value of e_trade_monthly_achievement.m_other_charge1
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Float getmOtherCharge1() {
        return mOtherCharge1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_monthly_achievement.m_other_charge1
     *
     * @param mOtherCharge1 the value for e_trade_monthly_achievement.m_other_charge1
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setmOtherCharge1(Float mOtherCharge1) {
        this.mOtherCharge1 = mOtherCharge1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_monthly_achievement.m_other_charge2
     *
     * @return the value of e_trade_monthly_achievement.m_other_charge2
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Float getmOtherCharge2() {
        return mOtherCharge2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_monthly_achievement.m_other_charge2
     *
     * @param mOtherCharge2 the value for e_trade_monthly_achievement.m_other_charge2
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setmOtherCharge2(Float mOtherCharge2) {
        this.mOtherCharge2 = mOtherCharge2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_monthly_achievement.m_other_charge3
     *
     * @return the value of e_trade_monthly_achievement.m_other_charge3
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Float getmOtherCharge3() {
        return mOtherCharge3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_monthly_achievement.m_other_charge3
     *
     * @param mOtherCharge3 the value for e_trade_monthly_achievement.m_other_charge3
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setmOtherCharge3(Float mOtherCharge3) {
        this.mOtherCharge3 = mOtherCharge3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_monthly_achievement.m_fixed_charge1
     *
     * @return the value of e_trade_monthly_achievement.m_fixed_charge1
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Float getmFixedCharge1() {
        return mFixedCharge1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_monthly_achievement.m_fixed_charge1
     *
     * @param mFixedCharge1 the value for e_trade_monthly_achievement.m_fixed_charge1
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setmFixedCharge1(Float mFixedCharge1) {
        this.mFixedCharge1 = mFixedCharge1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_monthly_achievement.m_fixed_charge2
     *
     * @return the value of e_trade_monthly_achievement.m_fixed_charge2
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Float getmFixedCharge2() {
        return mFixedCharge2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_monthly_achievement.m_fixed_charge2
     *
     * @param mFixedCharge2 the value for e_trade_monthly_achievement.m_fixed_charge2
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setmFixedCharge2(Float mFixedCharge2) {
        this.mFixedCharge2 = mFixedCharge2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_monthly_achievement.m_fixed_charge3
     *
     * @return the value of e_trade_monthly_achievement.m_fixed_charge3
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Float getmFixedCharge3() {
        return mFixedCharge3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_monthly_achievement.m_fixed_charge3
     *
     * @param mFixedCharge3 the value for e_trade_monthly_achievement.m_fixed_charge3
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setmFixedCharge3(Float mFixedCharge3) {
        this.mFixedCharge3 = mFixedCharge3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_monthly_achievement.update_dates
     *
     * @return the value of e_trade_monthly_achievement.update_dates
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Date getUpdateDates() {
        return updateDates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_monthly_achievement.update_dates
     *
     * @param updateDates the value for e_trade_monthly_achievement.update_dates
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setUpdateDates(Date updateDates) {
        this.updateDates = updateDates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_monthly_achievement.customer_volume
     *
     * @return the value of e_trade_monthly_achievement.customer_volume
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Integer getCustomerVolume() {
        return customerVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_monthly_achievement.customer_volume
     *
     * @param customerVolume the value for e_trade_monthly_achievement.customer_volume
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setCustomerVolume(Integer customerVolume) {
        this.customerVolume = customerVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_monthly_achievement.car_volume
     *
     * @return the value of e_trade_monthly_achievement.car_volume
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Integer getCarVolume() {
        return carVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_monthly_achievement.car_volume
     *
     * @param carVolume the value for e_trade_monthly_achievement.car_volume
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setCarVolume(Integer carVolume) {
        this.carVolume = carVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_monthly_achievement.creation_date
     *
     * @return the value of e_trade_monthly_achievement.creation_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_monthly_achievement.creation_date
     *
     * @param creationDate the value for e_trade_monthly_achievement.creation_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_monthly_achievement.created_by
     *
     * @return the value of e_trade_monthly_achievement.created_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_monthly_achievement.created_by
     *
     * @param createdBy the value for e_trade_monthly_achievement.created_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_monthly_achievement.update_date
     *
     * @return the value of e_trade_monthly_achievement.update_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_monthly_achievement.update_date
     *
     * @param updateDate the value for e_trade_monthly_achievement.update_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_monthly_achievement.updated_by
     *
     * @return the value of e_trade_monthly_achievement.updated_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_monthly_achievement.updated_by
     *
     * @param updatedBy the value for e_trade_monthly_achievement.updated_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_monthly_achievement.is_alive
     *
     * @return the value of e_trade_monthly_achievement.is_alive
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Boolean getIsAlive() {
        return isAlive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_monthly_achievement.is_alive
     *
     * @param isAlive the value for e_trade_monthly_achievement.is_alive
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setIsAlive(Boolean isAlive) {
        this.isAlive = isAlive;
    }
}