package net.ray.web.ees.db.eo;

import java.util.Date;

public class TradeDailyAchievement {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_daily_achievement.id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_daily_achievement.brand_id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Integer brandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_daily_achievement.mall_id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Integer mallId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_daily_achievement.sales_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Date salesDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_daily_achievement.sales_amount
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Float salesAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_daily_achievement.sales_volume
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Float salesVolume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_daily_achievement.sales_count
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Integer salesCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_daily_achievement.is_holiday
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String isHoliday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_daily_achievement.holiday_id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Integer holidayId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_daily_achievement.date_type
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String dateType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_daily_achievement.dayofweek
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String dayofweek;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_daily_achievement.week_num
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Integer weekNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_daily_achievement.weather
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String weather;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_daily_achievement.customer_volume
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Integer customerVolume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_daily_achievement.car_volume
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Integer carVolume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_daily_achievement.creation_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Date creationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_daily_achievement.created_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_daily_achievement.update_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_daily_achievement.update_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_daily_achievement.is_alive
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Boolean isAlive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_daily_achievement.id
     *
     * @return the value of e_trade_daily_achievement.id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_daily_achievement.id
     *
     * @param id the value for e_trade_daily_achievement.id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_daily_achievement.brand_id
     *
     * @return the value of e_trade_daily_achievement.brand_id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_daily_achievement.brand_id
     *
     * @param brandId the value for e_trade_daily_achievement.brand_id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_daily_achievement.mall_id
     *
     * @return the value of e_trade_daily_achievement.mall_id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Integer getMallId() {
        return mallId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_daily_achievement.mall_id
     *
     * @param mallId the value for e_trade_daily_achievement.mall_id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setMallId(Integer mallId) {
        this.mallId = mallId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_daily_achievement.sales_date
     *
     * @return the value of e_trade_daily_achievement.sales_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Date getSalesDate() {
        return salesDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_daily_achievement.sales_date
     *
     * @param salesDate the value for e_trade_daily_achievement.sales_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setSalesDate(Date salesDate) {
        this.salesDate = salesDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_daily_achievement.sales_amount
     *
     * @return the value of e_trade_daily_achievement.sales_amount
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Float getSalesAmount() {
        return salesAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_daily_achievement.sales_amount
     *
     * @param salesAmount the value for e_trade_daily_achievement.sales_amount
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setSalesAmount(Float salesAmount) {
        this.salesAmount = salesAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_daily_achievement.sales_volume
     *
     * @return the value of e_trade_daily_achievement.sales_volume
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Float getSalesVolume() {
        return salesVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_daily_achievement.sales_volume
     *
     * @param salesVolume the value for e_trade_daily_achievement.sales_volume
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setSalesVolume(Float salesVolume) {
        this.salesVolume = salesVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_daily_achievement.sales_count
     *
     * @return the value of e_trade_daily_achievement.sales_count
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Integer getSalesCount() {
        return salesCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_daily_achievement.sales_count
     *
     * @param salesCount the value for e_trade_daily_achievement.sales_count
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setSalesCount(Integer salesCount) {
        this.salesCount = salesCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_daily_achievement.is_holiday
     *
     * @return the value of e_trade_daily_achievement.is_holiday
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getIsHoliday() {
        return isHoliday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_daily_achievement.is_holiday
     *
     * @param isHoliday the value for e_trade_daily_achievement.is_holiday
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setIsHoliday(String isHoliday) {
        this.isHoliday = isHoliday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_daily_achievement.holiday_id
     *
     * @return the value of e_trade_daily_achievement.holiday_id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Integer getHolidayId() {
        return holidayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_daily_achievement.holiday_id
     *
     * @param holidayId the value for e_trade_daily_achievement.holiday_id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setHolidayId(Integer holidayId) {
        this.holidayId = holidayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_daily_achievement.date_type
     *
     * @return the value of e_trade_daily_achievement.date_type
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getDateType() {
        return dateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_daily_achievement.date_type
     *
     * @param dateType the value for e_trade_daily_achievement.date_type
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setDateType(String dateType) {
        this.dateType = dateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_daily_achievement.dayofweek
     *
     * @return the value of e_trade_daily_achievement.dayofweek
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getDayofweek() {
        return dayofweek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_daily_achievement.dayofweek
     *
     * @param dayofweek the value for e_trade_daily_achievement.dayofweek
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setDayofweek(String dayofweek) {
        this.dayofweek = dayofweek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_daily_achievement.week_num
     *
     * @return the value of e_trade_daily_achievement.week_num
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Integer getWeekNum() {
        return weekNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_daily_achievement.week_num
     *
     * @param weekNum the value for e_trade_daily_achievement.week_num
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setWeekNum(Integer weekNum) {
        this.weekNum = weekNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_daily_achievement.weather
     *
     * @return the value of e_trade_daily_achievement.weather
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getWeather() {
        return weather;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_daily_achievement.weather
     *
     * @param weather the value for e_trade_daily_achievement.weather
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setWeather(String weather) {
        this.weather = weather;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_daily_achievement.customer_volume
     *
     * @return the value of e_trade_daily_achievement.customer_volume
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Integer getCustomerVolume() {
        return customerVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_daily_achievement.customer_volume
     *
     * @param customerVolume the value for e_trade_daily_achievement.customer_volume
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setCustomerVolume(Integer customerVolume) {
        this.customerVolume = customerVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_daily_achievement.car_volume
     *
     * @return the value of e_trade_daily_achievement.car_volume
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Integer getCarVolume() {
        return carVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_daily_achievement.car_volume
     *
     * @param carVolume the value for e_trade_daily_achievement.car_volume
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setCarVolume(Integer carVolume) {
        this.carVolume = carVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_daily_achievement.creation_date
     *
     * @return the value of e_trade_daily_achievement.creation_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_daily_achievement.creation_date
     *
     * @param creationDate the value for e_trade_daily_achievement.creation_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_daily_achievement.created_by
     *
     * @return the value of e_trade_daily_achievement.created_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_daily_achievement.created_by
     *
     * @param createdBy the value for e_trade_daily_achievement.created_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_daily_achievement.update_date
     *
     * @return the value of e_trade_daily_achievement.update_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_daily_achievement.update_date
     *
     * @param updateDate the value for e_trade_daily_achievement.update_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_daily_achievement.update_by
     *
     * @return the value of e_trade_daily_achievement.update_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_daily_achievement.update_by
     *
     * @param updateBy the value for e_trade_daily_achievement.update_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_daily_achievement.is_alive
     *
     * @return the value of e_trade_daily_achievement.is_alive
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Boolean getIsAlive() {
        return isAlive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_daily_achievement.is_alive
     *
     * @param isAlive the value for e_trade_daily_achievement.is_alive
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setIsAlive(Boolean isAlive) {
        this.isAlive = isAlive;
    }
}