package net.ray.web.ees.db.eo;

import java.util.Date;

public class TradeType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_type.id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_type.trade_name
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String tradeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_type.trade_level
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Integer tradeLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_type.brand_number
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String brandNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_type.type_area
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Float typeArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_type.parent_id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_type.root_id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Integer rootId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_type.creation_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Date creationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_type.created_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_type.update_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_type.updated_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_trade_type.is_alive
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    private Boolean isAlive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_type.id
     *
     * @return the value of e_trade_type.id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_type.id
     *
     * @param id the value for e_trade_type.id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_type.trade_name
     *
     * @return the value of e_trade_type.trade_name
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getTradeName() {
        return tradeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_type.trade_name
     *
     * @param tradeName the value for e_trade_type.trade_name
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setTradeName(String tradeName) {
        this.tradeName = tradeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_type.trade_level
     *
     * @return the value of e_trade_type.trade_level
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Integer getTradeLevel() {
        return tradeLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_type.trade_level
     *
     * @param tradeLevel the value for e_trade_type.trade_level
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setTradeLevel(Integer tradeLevel) {
        this.tradeLevel = tradeLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_type.brand_number
     *
     * @return the value of e_trade_type.brand_number
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getBrandNumber() {
        return brandNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_type.brand_number
     *
     * @param brandNumber the value for e_trade_type.brand_number
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setBrandNumber(String brandNumber) {
        this.brandNumber = brandNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_type.type_area
     *
     * @return the value of e_trade_type.type_area
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Float getTypeArea() {
        return typeArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_type.type_area
     *
     * @param typeArea the value for e_trade_type.type_area
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setTypeArea(Float typeArea) {
        this.typeArea = typeArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_type.parent_id
     *
     * @return the value of e_trade_type.parent_id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_type.parent_id
     *
     * @param parentId the value for e_trade_type.parent_id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_type.root_id
     *
     * @return the value of e_trade_type.root_id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Integer getRootId() {
        return rootId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_type.root_id
     *
     * @param rootId the value for e_trade_type.root_id
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setRootId(Integer rootId) {
        this.rootId = rootId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_type.creation_date
     *
     * @return the value of e_trade_type.creation_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_type.creation_date
     *
     * @param creationDate the value for e_trade_type.creation_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_type.created_by
     *
     * @return the value of e_trade_type.created_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_type.created_by
     *
     * @param createdBy the value for e_trade_type.created_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_type.update_date
     *
     * @return the value of e_trade_type.update_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_type.update_date
     *
     * @param updateDate the value for e_trade_type.update_date
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_type.updated_by
     *
     * @return the value of e_trade_type.updated_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_type.updated_by
     *
     * @param updatedBy the value for e_trade_type.updated_by
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_trade_type.is_alive
     *
     * @return the value of e_trade_type.is_alive
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public Boolean getIsAlive() {
        return isAlive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_trade_type.is_alive
     *
     * @param isAlive the value for e_trade_type.is_alive
     *
     * @mbg.generated Thu Nov 24 17:04:55 CST 2016
     */
    public void setIsAlive(Boolean isAlive) {
        this.isAlive = isAlive;
    }
}